name: .NET Core Build Validation

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build and Validate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x  

    - name: Restore dependencies
      working-directory: ./
      run: dotnet restore wx.sln

    - name: Build solution
      working-directory: ./
      run: dotnet build wx.sln --configuration Release --no-restore

      if: success()
    
    - name: Check Build Status
      if: always()
      run: |
        if [ $? -ne 0 ]; then
          echo "Build failed"
          exit 1
        fi